export const EMERGENCY_SYMPTOMS = [
  'chest pain', 'chest pressure', 'heart attack',
  'difficulty breathing', "can't breathe", 'shortness of breath severe',
  'sudden severe headache', 'worst headache of my life',
  'face drooping', 'arm weakness sudden', 'speech difficulty sudden',
  'severe upper right abdominal pain',
  'coughing blood', 'vomiting blood',
  'severe allergic reaction', 'throat closing',
  'loss of consciousness', 'passing out',
];

export function checkForEmergency(text: string): boolean {
  return EMERGENCY_SYMPTOMS.some(symptom =>
    text.toLowerCase().includes(symptom.toLowerCase())
  );
}

export const EMERGENCY_RESPONSE = `IMPORTANT: The symptom you described may require immediate medical attention. Please call 911 or go to your nearest emergency room immediately. Do not use this app for emergency medical situations. CauseHealth is an educational tool and cannot provide emergency medical care.`;

export const STANDARD_DISCLAIMER = `This analysis is generated by CauseHealth AI for educational purposes only. It is not medical advice, does not constitute a diagnosis, and does not replace evaluation by a licensed healthcare provider. Always discuss findings with your doctor before making changes to medications, supplements, or health practices. In case of emergency, call 911 immediately.`;
